# Generated by Django 6.1.1 on 2026-10-03 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(40),
                        ],
                        verbose_name="رقم الجهاز",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=60, verbose_name="الاسم"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "is_absent",
                    models.BooleanField(default=False, verbose_name="الطالب غائب"),
                ),
                (
                    "is_blocked",
                    models.BooleanField(default=False, verbose_name="محظور (مقفول)"),
                ),
            ],
            options={
                "verbose_name": "جهاز",
                "verbose_name_plural": "الأجهزة",
                "ordering": ["number"],
            },
        ),
    ]
